### ISSUE TITLE
installDist fails with error: cannot find symbol return buildRequestMetaData.getBuildTimeClock().getStartTime();

### ISSUE THREAD

**Issue by vanniktech** [gradle/gradle-profiler#107]
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)
```

Is what I'm using for building. I'm on 3fd498c421f99d122feeac79f0eb0d14c31fc41d

**Comment by oehme** [comment]
Please use the `./gradlew` script, not your own Gradle installation.

**Comment by vanniktech** [comment]
That seems to work however when executing your command from the tweet `gradle-profiler --profile jfr --warmups 20 --iterations 20 help` I'm not getting further than:

```

* Stopping daemons
Stopping Daemon(s)
1 Daemon stopped

* Scenarios
Scenario: using Gradle 5.1
  Gradle 5.1 (/home/niklas/dev/vanniktech/gradle-user-home/wrapper/dists/gradle-5.1-all/agkdmobix61yocaldxqz74wpx/gradle-5.1)
  Run using: ToolingApi
  Cleanup Tasks: []
  Tasks: [help]
  Gradle args: []
  Build changes: none
  Warm-ups: 20
  Builds: 20

* Running scenario using Gradle 5.1 (scenario 1/1)

* Stopping daemonsgradle-profiler --profile jfr --warmups 20 --iterations 20 help
No Gradle daemons are running.

* Build details
Gradle version: Gradle 5.1
Java home: /usr/lib/jvm/java-8-openjdk-amd64
OS name: Linux 4.18.0-13-generic
JVM args:
  -XX:MaxMetaspaceSize=256m
  -XX:+HeapDumpOnOutOfMemoryError
  -Xmx512m
  -Dfile.encoding=UTF-8
  -Duser.country=US
  -Duser.language=en
  -Duser.variant
  -Dorg.gradle.profiler.scenario=default
  -XX:+UnlockCommercialFeatures
  -XX:+FlightRecorder
  -XX:FlightRecorderOptions=stackdepth=1024
  -XX:+UnlockDiagnosticVMOptions
  -XX:+DebugNonSafepoints
Gradle args:
  -I
  /tmp/gradleProfilerPidInstrumentation1258996329144094213.gradle
  --gradle-user-home
  /home/niklas/dev/vanniktech/gradle-user-home

* Running warm-up build #1 with build tasks [help]

ERROR: failed to run build. See log file for details.


* Stopping daemons
No Gradle daemons are running.
org.gradle.tooling.GradleConnectionException: Could not execute build using Gradle installation '/home/niklas/dev/vanniktech/gradle-user-home/wrapper/dists/gradle-5.1-all/agkdmobix61yocaldxqz74wpx/gradle-5.1'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:77)
	at org.gradle.profiler.ToolingApiInvoker.lambda$run$0(ToolingApiInvoker.java:28)
	at org.gradle.profiler.BuildInvoker.run(BuildInvoker.java:55)
	at org.gradle.profiler.ToolingApiInvoker.run(ToolingApiInvoker.java:24)
	at org.gradle.profiler.BuildInvoker.runBuild(BuildInvoker.java:37)
	at org.gradle.profiler.Main.lambda$runGradleScenario$0(Main.java:180)
	at org.gradle.profiler.Main.tryRun(Main.java:422)
	at org.gradle.profiler.Main.runGradleScenario(Main.java:180)
	at org.gradle.profiler.Main.run(Main.java:85)
	at org.gradle.profiler.Main.main(Main.java:32)
Caused by: org.gradle.api.GradleException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/5.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'UnlockCommercialFeatures'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

	at org.gradle.launcher.daemon.client.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:35)
	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:178)
	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:140)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:212)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startDaemon(DefaultDaemonConnector.java:206)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:130)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:139)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:94)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:50)
	at org.gradle.tooling.internal.provider.DaemonBuildActionExecuter.execute(DaemonBuildActionExecuter.java:35)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.LoggingBridgingBuildActionExecuter.execute(LoggingBridgingBuildActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:192)
	at org.gradle.tooling.internal.provider.ProviderConnection.run(ProviderConnection.java:135)
	at org.gradle.tooling.internal.provider.DefaultConnection.getModel(DefaultConnection.java:193)
	at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:53)
	at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:41)
	at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:59)
	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:47)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:89)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher$1.run(DefaultBuildLauncher.java:83)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:84)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

* Results written to /home/niklas/dev/vanniktech/profile-out-2
```

**Comment by oehme** [comment]
Java Flight Recorder is only part of Open JKD since Java 11. For lower versions you need to use Oracle JDK. I'll add a better error message for that.

**Comment by vanniktech** [comment]
`java -version` yields:

```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)
```

Should not I be good to go then?

**Comment by oehme** [comment]
`Java home: /usr/lib/jvm/java-8-openjdk-amd64` is what Gradle says. Check your gradle.properties for `org.gradle.javahome`.

**Comment by vanniktech** [comment]
Getting further. After the 20th run I'm hitting:

```
java.lang.RuntimeException: Could not find 'jcmd' executable for Java home directory /usr/lib/jvm/java-11-openjdk-amd64
	at org.gradle.profiler.jfr.JFRControl.<init>(JFRControl.java:25)
	at org.gradle.profiler.jfr.JfrProfiler.newController(JfrProfiler.java:79)
	at org.gradle.profiler.Main.runGradleScenario(Main.java:189)
	at org.gradle.profiler.Main.run(Main.java:85)
	at org.gradle.profiler.Main.main(Main.java:32)
```

**Comment by oehme** [comment]
That's really odd, please check for the `jcmd` executable in your Java installation. It should ship with every JDK.

**Comment by vanniktech** [comment]
Sweet seems like I only had the JRE installed. Works fabulously now. Thanks for the help. Regarding the last RuntimeException, it might make sense to catch that and hint that possibly only the JRE and not the full JDK is installed.

**Comment by oehme** [comment]
Agreed, I'll improve the error handling.
