### ISSUE TITLE
NPE when running with clear-transform-cache-before

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle-profiler#122]
Running the Gradle Profiler @ a8a6e9599 and getting this error running a scenario:

```
* Stopping daemons
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.gradle.profiler.mutations.ClearArtifactTransformCacheMutator.filesAsStream(ClearArtifactTransformCacheMutator.java:28)
	at org.gradle.profiler.mutations.ClearArtifactTransformCacheMutator.cleanupCacheDir(ClearArtifactTransformCacheMutator.java:20)
	at org.gradle.profiler.mutations.AbstractCleanupMutator.doCleanup(AbstractCleanupMutator.java:52)
	at org.gradle.profiler.mutations.AbstractCleanupMutator.beforeBuild(AbstractCleanupMutator.java:25)
	at org.gradle.profiler.ScenarioInvoker.runMeasured(ScenarioInvoker.java:42)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:121)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:24)
	at org.gradle.profiler.ScenarioInvoker.run(ScenarioInvoker.java:22)
	at org.gradle.profiler.Main.run(Main.java:77)
	at org.gradle.profiler.Main.main(Main.java:16)

```

The scenario looks like this:

```
cleanBuild {
  cleanup-tasks = ["clean"]
  tasks = [":phthalic:assembleDebug"]
   clear-transform-cache-before = BUILD
}
```

**Comment by adammurdoch** [comment]
It looks like this can happen when there is a file (not a directory) whose name starts with `transforms-` in the `gradle-user-home` directory used by the profiler. I'll fix this soon.

**Comment by adammurdoch** [comment]
This is fixed via https://github.com/gradle/gradle-profiler/pull/123
