### ISSUE TITLE
Add option to ignore build failures

### ISSUE THREAD

**Issue by vRallev** [gradle/gradle-profiler#202]
We're using the Gradle Profiler for benchmarks. Unfortunately, some tools like Kotlin and KAPT are flaky and sometimes cause build failures, e.g.
```
Caused by: java.lang.NullPointerException
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1155)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1188)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1179)
	at kotlinx.metadata.impl.extensions.MetadataExtensions$Companion$INSTANCES$2.invoke(MetadataExtensions.kt:63)
	at kotlinx.metadata.impl.extensions.MetadataExtensions$Companion$INSTANCES$2.invoke(MetadataExtensions.kt:61)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at kotlinx.metadata.impl.extensions.MetadataExtensions$Companion.getINSTANCES(MetadataExtensions.kt)
```
The Gradle Profiler stops this scenario and moves on with the next one. I think this happens here: https://github.com/gradle/gradle-profiler/blob/29796bde64b215984c5620568efc62c513886705/src/main/java/org/gradle/profiler/GradleScenarioInvoker.java#L158

It would be great to tell the profiler to either repeat this build or to ignore this one single result and continue with the next build, but don't stop the entire scenario. Right now single scenarios need to be manually repeated and that's very time consuming.

**Comment by rcgonzalezf** [comment]
This is definitely something will be nice to add, especially because of KAPT issues, is very frustrating to see that scenarios fail in the last iteration and lose the data :(

**Comment by ov7a** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.
