### ISSUE TITLE
Gradle runs out of memory when stopping daemons

### ISSUE THREAD

**Issue by vRallev** [gradle/gradle-profiler#203]
We have a fairly large project and run the Gradle Profiler in CI. I often see that benchmarks finish successfully, but Gradle runs out of memory when stopping the daemons. 

This is the log. Notice that it starts with the last measured build.
```
BUILD SUCCESSFUL in 1m 41s
2223 actionable tasks: 2223 executed
A build scan will not be published due to this build running offline.
Used daemon with pid 700
Time to task execution 
Execution time 101635 ms

* Stopping daemons
Running command /some/path/gradle-user-home/wrapper/dists/gradle-6.4-all/h8pi7famayzdg9sl28jayaip/gradle-6.4/bin/gradle --stop --gradle-user-home /some/path/gradle-user-home
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000028fa00000, 8950644736, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 8950644736 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /some/path/hs_err_pid21696.log
java.lang.RuntimeException: Could not run command /some/path/gradle-user-home/wrapper/dists/gradle-6.4-all/h8pi7famayzdg9sl28jayaip/gradle-6.4/bin/gradle --stop --gradle-user-home /some/path/gradle-user-home
Output:
======
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000028fa00000, 8950644736, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 8950644736 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /some/path/hs_err_pid21696.log
======
	at org.gradle.profiler.CommandExec$RunHandle.waitForSuccess(CommandExec.java:178)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:68)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:34)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:29)
	at org.gradle.profiler.GradleBuildConfiguration.runGradle(GradleBuildConfiguration.java:59)
	at org.gradle.profiler.DaemonControl.stop(DaemonControl.java:14)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:191)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:24)
	at org.gradle.profiler.ScenarioInvoker.run(ScenarioInvoker.java:24)
	at org.gradle.profiler.Main.run(Main.java:77)
	at org.gradle.profiler.Main.main(Main.java:16)

* Results written to /some/path/profile-out
  /some/path/profile-out/benchmark.csv
  /some/path/profile-out/benchmark.html
```
Notice that the results are still written to disk. Nonetheless it's annoying to see the process crash. As far as I can tell there is no easy way to bump the memory for the Gradle task stopping all daemons: https://github.com/gradle/gradle-profiler/blob/5d707961de868b8ba104b1bc8817b7963c04c91a/src/main/java/org/gradle/profiler/DaemonControl.java#L14

**Comment by Recognized** [comment]
+1 to the issue. For me, results are not written, so gradle-profiler just doesn't work for big enough projects. Tried to use _JAVA_OPTIONS="-Xmx16G", but no luck.

**Comment by tresat** [comment]
Sorry for the late reply.

If this is still occurring, please provide a reproducer, and we will mark it as a valid issue.  However, we suspect that this has been fixed by improvements in recent versions of Gradle.

Is it possible that you are running an extremely large number of daemons when this occurs?
