### ISSUE TITLE
Iterations option not working in screnario file

### ISSUE THREAD

**Issue by diklimchuk** [gradle/gradle-profiler#225]
gradle-profiler doesn't recognize the iterations option in scenario files and fails with an exception

Used configuration:
Scenario file:
```
default-scenarios = ["clean_build"]

clean_build {
    title = "Clean Build"
    tasks = [":app:aMD"]
    cleanup-tasks = ["clean"]
    run-using = cli 
    daemon = warm
    measured-build-ops = ["org.gradle.api.internal.tasks.SnapshotTaskInputsBuildOperationType"]
    warm-ups = 4
    iterations = 6
}
```

Log: 
```
* Settings
Project dir: .
Output dir: profile-out-4
Profiler: none
Benchmark: true
Versions: []
Gradle User Home: gradle-user-home
Targets: []
java.lang.IllegalArgumentException: Unrecognized key 'clean_build.iterations' defined in scenario file profiler-scenarios
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:200)
	at org.gradle.profiler.ScenarioLoader.doLoadScenarios(ScenarioLoader.java:146)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:127)
	at org.gradle.profiler.Main.run(Main.java:44)
	at org.gradle.profiler.Main.main(Main.java:16)
```

**Comment by wolfs** [comment]
The option has been introduced by https://github.com/gradle/gradle-profiler/pull/208.

What version of Gradle profiler are you using? I don't think the change is part of any released version, so you need to build `gradle-profiler` from source to use it.

**Comment by diklimchuk** [comment]
Yeap, i was using a version from sdkman. Closing the issue.
