### ISSUE TITLE
Is it possible to specify path to gradle executable to use?

### ISSUE THREAD

**Issue by hiteshsharma** [gradle/gradle-profiler#279]
My organization uses our custom fork of gradle for builds and it seems gradle-profiler always uses the original gradle. Is it possible to specify the gradle executable to be used?

**Comment by wolfs** [comment]
You can use `--gradle-version <path to your installation>` on the command line to point to a custom installation.

**Comment by hiteshsharma** [comment]
Thanks for the response but when I'm specifying the path to the executable, it's throwing error for the unrecognized version. Where can I find what versions are supported? My fork is based on gradle 5.6.4

```
$ gradle-profiler --benchmark --gradle-version /usr/local/bin/fgradle  --project-dir . build  

* Writing results to /Users/hsharma/Workspace/messaging/messaging-delivery-mt_trunk/profile-out-12

* Settings
Project dir: .
Output dir: profile-out-12
Profiler: none
Benchmark: true
Versions: [/usr/local/bin/fgradle]
Gradle User Home: gradle-user-home
Targets: [build]

* Inspecting the build using Gradle version '/usr/local/bin/fgradle'
java.lang.IllegalArgumentException: Unrecognized Gradle version '/usr/local/bin/fgradle' specified.
	at org.gradle.profiler.DefaultGradleBuildConfigurationReader.doResolveVersion(DefaultGradleBuildConfigurationReader.java:82)
	at org.gradle.profiler.DefaultGradleBuildConfigurationReader.readConfiguration(DefaultGradleBuildConfigurationReader.java:62)
	at org.gradle.profiler.ScenarioLoader.adhocScenarios(ScenarioLoader.java:135)
	at org.gradle.profiler.ScenarioLoader.doLoadScenarios(ScenarioLoader.java:127)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:106)
	at org.gradle.profiler.Main.run(Main.java:44)
	at org.gradle.profiler.Main.main(Main.java:16
```

**Comment by wolfs** [comment]
You should pass the location of the Gradle home to `--gradle-version`, not the location of the executable.
