### ISSUE TITLE
Problem getting Android Studio Sync scan to run in v0.15.0

### ISSUE THREAD

**Issue by alsutton** [gradle/gradle-profiler#291]
We have an Android Studio Sync scenario which looks like this;

```
androidStudioSync {
  title = "Android Studio Sync"
  android-studio-sync {
  }
}
```

which I run using the following script;

```
export PATH=~/workspace/gradle-profiler/build/install/gradle-profiler/bin:"$PATH"
TIMESTAMP=`date +%H%M%S`

gradle-profiler --benchmark --output-dir ~/benchmark-$TIMESTAMP --scenario-file tools/scripts/gradle_profiler/profiler.scenarios --gradle-user-home ~/gradle-user-home-$TIMESTAMP --studio-install-dir /Applications/Android\ Studio.app androidStudioSync
```

With v0.14.0 the benchmark completes as expected. With v0.15.0 the script fails with the following output;

```
.
.
.
* Starting Android Studio at /Applications/Android Studio.app

* Java command: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
* Classpath:
  /Applications/Android Studio.app/Contents/lib/bootstrap.jar
  /Applications/Android Studio.app/Contents/lib/extensions.jar
  /Applications/Android Studio.app/Contents/lib/util.jar
  /Applications/Android Studio.app/Contents/lib/jdom.jar
  /Applications/Android Studio.app/Contents/lib/log4j.jar
  /Applications/Android Studio.app/Contents/lib/trove4j.jar
  /Applications/Android Studio.app/Contents/lib/jna.jar
* System properties:
  idea.platform.prefix -> AndroidStudio
  idea.paths.selector -> AndroidStudio4.1
  idea.executable -> studio
  idea.vendor.name -> Google
  idea.home.path -> /Applications/Android Studio.app/Contents
* Main class: com.intellij.idea.Main
* Using command line: [/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java, -cp, /Applications/Android Studio.app/Contents/lib/bootstrap.jar:/Applications/Android Studio.app/Contents/lib/extensions.jar:/Applications/Android Studio.app/Contents/lib/util.jar:/Applications/Android Studio.app/Contents/lib/jdom.jar:/Applications/Android Studio.app/Contents/lib/log4j.jar:/Applications/Android Studio.app/Contents/lib/trove4j.jar:/Applications/Android Studio.app/Contents/lib/jna.jar, -Didea.platform.prefix=AndroidStudio, -Didea.paths.selector=AndroidStudio4.1, -Didea.executable=studio, -Didea.vendor.name=Google, -Didea.home.path=/Applications/Android Studio.app/Contents, -javaagent:/private/var/folders/mk/n88wc_415z3736dm38c6tch40000gp/T/studio-agent12717994519169223622jar=53105,/private/var/folders/mk/n88wc_415z3736dm38c6tch40000gp/T/instrumentation-support8260472652491390060jar, --add-exports, java.base/jdk.internal.misc=ALL-UNNAMED, -Xbootclasspath/a:/private/var/folders/mk/n88wc_415z3736dm38c6tch40000gp/T/asm16612655738369206703jar:/private/var/folders/mk/n88wc_415z3736dm38c6tch40000gp/T/client-protocol7507291653024805901jar, com.intellij.idea.Main, /Users/als/workspace/myapp-android]
java.lang.IllegalStateException: Timeout waiting for incoming connection from agent.
	at org.gradle.profiler.client.protocol.Server.waitForIncoming(Server.java:50)
	at org.gradle.profiler.studio.StudioGradleClient.<init>(StudioGradleClient.java:43)
	at org.gradle.profiler.GradleClientSpec$4.create(GradleClientSpec.java:64)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:73)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:21)
	at org.gradle.profiler.ScenarioInvoker.run(ScenarioInvoker.java:17)
	at org.gradle.profiler.Main.invoke(Main.java:110)
	at org.gradle.profiler.Main.run(Main.java:76)
	at org.gradle.profiler.Main.main(Main.java:18)
```

I'm using a checkout directly from this repo and have used the v0.14.0 and v0.15.0 tags to move the version of the profiler forwards and backwards between versions.

If I use the command shown by the profiler as starting IntelliJ I get the following error;

![Screenshot 2020-11-02 at 12 43 49](https://user-images.githubusercontent.com/430714/97875442-4c339d80-1d12-11eb-91e4-61b3cf76d5c9.png)

Is there anything I can do to either extend the timeout which is failing, or confirm what the timeout is for and see if I can fix the error?

**Comment by alsutton** [comment]
This seems to be an issue with AS 4.1.x. Using AS 4.2-beta doesn't trigger this problem.
