### ISSUE TITLE
Support for JProfiler 10

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle-profiler#30]
When running gradle profiler with JProfiler 10 installed I get the following exception:
```
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.NameNotFoundException: jmxrmi
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:249)
	at org.gradle.profiler.jprofiler.JProfilerController.ensureConnected(JProfilerController.java:131)
	at org.gradle.profiler.jprofiler.JProfilerController.invoke(JProfilerController.java:158)
	at org.gradle.profiler.jprofiler.JProfilerController.startNow(JProfilerController.java:73)
	at org.gradle.profiler.jprofiler.JProfilerController.start(JProfilerController.java:39)
	at org.gradle.profiler.Main.runGradleScenario(Main.java:203)
	at org.gradle.profiler.Main.run(Main.java:74)
	at org.gradle.profiler.Main.main(Main.java:24)
Caused by: javax.naming.NameNotFoundException: jmxrmi
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:120)
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
	... 8 more
```

Any ideas?

**Comment by wolfs** [comment]
Looks like this has been a network issue on my side 😞 . Closing.
