### ISSUE TITLE
Make warmup parameter more customizable

### ISSUE THREAD

**Issue by pvegh** [gradle/gradle-profiler#327]
I'd like to be able to set warmup to be 0. Currently the minimum is 1.

It should be my decision because:
* maybe I want to test on current temperatures
* maybe it's e.g. a Laptop and warming it up even more defies the purpose of my testing

Also warmup for the 2nd and later measured builds seem unnecessary to me since we're already warmed up.
Consecutive warmups make the machine uselessly hot and slow if it's e.g. a laptop. Maybe it's NOT what I want to be measuring.

**Comment by IgnatBeresnev** [comment]
Our plugin is expericning OOM issues and the only build I can reliably reproduce it on takes 3 hours to build. I'd really like to skip the warmup part and just profile the heap with async profiler (also not even sure if warmup makes sense for heap profiling)

**Comment by mr1chter** [comment]
I want to add that the most simple case of profiling a build will always warm up not only the daemon, but also the project, giving UP-TO-DATE tasks everywhere. But there is no simple commandline option for cleanup-tasks, so the "Advanced profiling scenarios" have to be used even in the most simplest cases.

**Comment by rdehuyss** [comment]
I also tried setting warmup to `0` as our build also takes quite some time. The profiler failed immediately without any reason:

```
➜  jobrunr-pro git:(feature/v8/pro/carbon-aware-jobs) ✗ gradle-profiler --profile async-profiler-heap core:test --warmups 0 --iterations 1

* Writing results to /Users/rdehuyss/Projects/JobRunr/jobrunr-pro/profile-out-5

* Settings
Project dir: /Users/rdehuyss/Projects/JobRunr/jobrunr-pro
Output dir: /Users/rdehuyss/Projects/JobRunr/jobrunr-pro/profile-out-5
Profiler: async profiler
Benchmark: false
Versions: []
Gradle User Home: /Users/rdehuyss/Projects/JobRunr/jobrunr-pro/gradle-user-home
Targets: [core:test]
Warm-ups: 0
Builds: 1

* Inspecting the build using its default Gradle version

* Stopping daemons

There were some problems with the profiler configuration:
- Scenario using Gradle 8.5: You can not skip warm-ups when profiling or benchmarking a Gradle build. Use --no-daemon or --cold-daemon if you want to profile or benchmark JVM startup

java.lang.IllegalArgumentException: There were some problems with the profiler configuration. Please see the log output for details.
        at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:175)
        at org.gradle.profiler.Main.run(Main.java:68)
        at org.gradle.profiler.Main.main(Main.java:37)


```

**Comment by abstratt** [comment]
Same here. This could be a warning only. Also, I fail to see the value of warm-up builds for heap dump profiling.

**Comment by ljacomet** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.

***

If `--cold-daemon` effectively enables profiling a single execution, then its documentation should be updated.
