### ISSUE TITLE
Gradle Profiler NPE when using gradle-7.0

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle-profiler#330]
@fkruege commented on [Fri Apr 16 2021](https://github.com/gradle/gradle/issues/16872)

### Expected Behavior
Gradle profiler should not crash.

### Current Behavior
Gradle profiler is crashing with a NPE,

```
1: Task failed with an exception.
-----------
* What went wrong:
java.lang.NullPointerException (no error message)
* Try:
 Run with --scan to get full insights.
* Exception is:
java.lang.NullPointerException
	at org.gradle.profile.ProfileEventAdapter.beforeResolve(ProfileEventAdapter.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```
### Context
This is occurring in our prod app.  We have a gradle profiler job that captures build metrics and we use this to understand our build performance. This used to work in Gradle 6.8.3 but stopped working when we upgraded to Gradle 7.0. 

### Steps to Reproduce 

 I created a sample project that duplicates the error.

Sample project: https://github.com/fkruege/KotlinGradleProfilerNPE
Command to run: `gradle-profiler --gradle-user-home ./gradle_new --benchmark --iterations 1 --project-dir ./ --scenario-file ./profiler.scenarios ci_clean`

[log_crash.txt](https://github.com/gradle/gradle/files/6327542/log_crash.txt)

### Your Environment
Gradle Profiler 0.16

Build scan URL:

**Comment by bmuskalla** [comment]
Root cause seems to be in gradle. Following up on the [original issue](https://github.com/gradle/gradle/issues/16872)
