### ISSUE TITLE
Cannot parse a simple android resource integers file

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle-profiler#334]
Using this example, profiler fails to parse and edit the file

```
java.lang.IllegalArgumentException: Cannot parse source file /home/ubuntu/actions-runner/_work/.../src/main/res/values/integers.xml to apply changes
	at org.gradle.profiler.mutations.ApplyValueChangeToAndroidResourceFileMutator.applyChangeTo(ApplyValueChangeToAndroidResourceFileMutator.java:16)
	at org.gradle.profiler.mutations.AbstractFileChangeMutator.beforeBuild(AbstractFileChangeMutator.java:27)
	at org.gradle.profiler.CompositeBuildMutator.beforeBuild(CompositeBuildMutator.java:37)
	at org.gradle.profiler.CompositeBuildMutator.beforeBuild(CompositeBuildMutator.java:37)
	at org.gradle.profiler.RunBuildStepAction.run(RunBuildStepAction.java:26)
	at org.gradle.profiler.ScenarioInvoker.runMeasured(ScenarioInvoker.java:36)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:113)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:21)
	at org.gradle.profiler.ScenarioInvoker.run(ScenarioInvoker.java:17)
	at org.gradle.profiler.Main.invoke(Main.java:110)
	at org.gradle.profiler.Main.run(Main.java:76)
	at org.gradle.profiler.Main.main(Main.java:18)
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <integer name="nav_avatar_corner_radius">8</integer>
</resources>
```

**Comment by ZacSweers** [comment]
Doesn't work for booleans either

```
java.lang.IllegalArgumentException: Cannot parse source file /home/ubuntu/actions-runner/_work/.../src/main/res/values/booleans.xml to apply changes
	at org.gradle.profiler.mutations.ApplyValueChangeToAndroidResourceFileMutator.applyChangeTo(ApplyValueChangeToAndroidResourceFileMutator.java:16)
	at org.gradle.profiler.mutations.AbstractFileChangeMutator.beforeBuild(AbstractFileChangeMutator.java:27)
	at org.gradle.profiler.CompositeBuildMutator.beforeBuild(CompositeBuildMutator.java:37)
	at org.gradle.profiler.CompositeBuildMutator.beforeBuild(CompositeBuildMutator.java:37)
	at org.gradle.profiler.RunBuildStepAction.run(RunBuildStepAction.java:26)
	at org.gradle.profiler.ScenarioInvoker.runMeasured(ScenarioInvoker.java:36)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:113)
	at org.gradle.profiler.GradleScenarioInvoker.doRun(GradleScenarioInvoker.java:21)
	at org.gradle.profiler.ScenarioInvoker.run(ScenarioInvoker.java:17)
	at org.gradle.profiler.Main.invoke(Main.java:110)
	at org.gradle.profiler.Main.run(Main.java:76)
	at org.gradle.profiler.Main.main(Main.java:18)
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <bool name="profile_two_panel">false</bool>
</resources>
```

Does this feature maybe not work anymore?

**Comment by plastiv** [comment]
Works for strings only https://github.com/gradle/gradle-profiler/blob/91ccad2c57eccc29c3fe698284968828bd6c4ca1/src/main/java/org/gradle/profiler/mutations/ApplyValueChangeToAndroidResourceFileMutator.java#L14

**Comment by tresat** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.

***

This should work for XML and be properly documented.
