### ISSUE TITLE
NullPointerException in CsvGenerator when benchmarking

### ISSUE THREAD

**Issue by PawelKwiecinski** [gradle/gradle-profiler#338]
Consistently getting an NPE when running with these flags:
`--benchmark --cold-daemon --iterations=1 --measure-config-time --measure-gc`

```

Execution time 17471 ms

* Stopping daemons
java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.gradle.profiler.report.CsvGenerator.writeWideRow(CsvGenerator.java:116)
	at org.gradle.profiler.report.CsvGenerator.writeWide(CsvGenerator.java:99)
	at org.gradle.profiler.report.CsvGenerator.write(CsvGenerator.java:40)
	at org.gradle.profiler.report.AbstractGenerator.write(AbstractGenerator.java:20)
	at org.gradle.profiler.BenchmarkResultCollector.write(BenchmarkResultCollector.java:31)
	at org.gradle.profiler.Main.invoke(Main.java:119)
	at org.gradle.profiler.Main.run(Main.java:76)
	at org.gradle.profiler.Main.main(Main.java:18)
```

Scenarios file:
```
# Build scenarios files for gradle-profiler (https://github.com/gradle/gradle-profiler)

# --- Full builds ---
full_build_xxxxx_app {
    cleanup-tasks = ["clean"]
    tasks = [":apps:xxxxx:assemblePED"]
}



# --- Incremental builds ---
non_abi_change {
    tasks = [":apps:xxxxx:assemblePED"]
    apply-non-abi-change-to = ["file1path.kt", "file2path.kt"]
}

abi_change {
    tasks = [":apps:xxxxx:assemblePED"]
    apply-abi-change-to = ["file1path.kt", "file2path.kt"]
}

layout_change {
    tasks = [":apps:xxxxx:assemblePED"]
    apply-android-layout-change-to = "file3path.xml"
}

string_resource_change {
    tasks = [":apps:xxxxx:assemblePED"]
    apply-android-resource-value-change-to = "file4path.xml"
}



# --- IDE specific tasks ---
ideaModel {
    title = "IDEA model"
    # Fetch the IDEA tooling model
    model = "org.gradle.tooling.model.idea.IdeaProject"
}

#androidStudioSync {
#    title = "Android Studio Sync"
#    # Measure an Android studio sync
#    android-studio-sync {
#    }
#}

```

Version used: 0.16.0

**Comment by tresat** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.
