### ISSUE TITLE
failed to download the gradle version 

### ISSUE THREAD

**Issue by Hyeongseok-Lee** [gradle/gradle-profiler#354]
i'm trying gradle-profiler but suspended due to failure of downloading gradle like below message,
my network system is under proxy, how can i set network proxy for 'gradle-profiler'?

$ gradle-profiler --benchmark --project-dir . build --gradle-version="6.8.3"

* Settings
Project dir: .
Output dir: profile-out-11
Profiler: none
Benchmark: true
Versions: [6.8.3]
Targets: [build]

* Inspecting the build using Gradle version '6.8.3'
Downloading https://services.gradle.org/distributions/gradle-6.8.3-bin.zip

org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-6.8.3-bin.zip'.
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:139)
        at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:41)

**Comment by anthonymonori** [comment]
I'm seeing similar stacktrace to the above but I don't specify a `--gradle-version` but rather let it use the one defined by the project I'm inspecting.

**Comment by satyarths** [comment]
You can use `JAVA_TOOL_OPTIONS` env variable for this and setup the system properties for the java process to use.  
The properties to set can be found at https://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html.
