### ISSUE TITLE
Gradle Profiler fails with exception on JDK 17

### ISSUE THREAD

**Issue by inktomi** [gradle/gradle-profiler#398]
Hi! 

The latest versions of [Gradle support JDK 17](https://docs.gradle.org/current/userguide/compatibility.html), and so it would be great if the Gradle Profiler also supported it. When I run a profiler command using JDK 17 and Gradle 7.3.3 I get the following error:

```
* What went wrong:
Failed to create service 'pidCollector'.
> Could not create an instance of type org.gradle.trace.pid.PidCollectorBuildService.
   > Unable to make field private final sun.management.VMManagement sun.management.RuntimeImpl.jvm accessible: module java.management does not "opens sun.management" to unnamed module @4f2b58b8

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.services.internal.ServiceLifecycleException: Failed to create service 'pidCollector'.
	at org.gradle.api.services.internal.BuildServiceProvider.calculateOwnValue(BuildServiceProvider.java:116)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:235)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:212)
	at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$AbstractListener.run(DefaultBuildEventsListenerRegistry.java:154)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type org.gradle.trace.pid.PidCollectorBuildService.
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:69)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:55)
	at org.gradle.api.services.internal.BuildServiceProvider.calculateOwnValue(BuildServiceProvider.java:114)
	... 7 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.management.VMManagement sun.management.RuntimeImpl.jvm accessible: module java.management does not "opens sun.management" to unnamed module @4f2b58b8
	at org.gradle.trace.pid.PidCollectorBuildService.getPid(PidCollectorBuildService.java:40)
	at org.gradle.trace.pid.PidCollectorBuildService.<init>(PidCollectorBuildService.java:32)
	at org.gradle.trace.pid.PidCollectorBuildService$Inject.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2070)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:488)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	... 9 more
```

I'm reporting this here, as it seems to only happen when running with the Gradle Profiler. We are using it on an Android project, with the Android Gradle Plugin version 7.1.0 though I don't think that's needed to reproduce the error. Let me know if This isn't the proper place, I'm happy to report this elsewhere if needed.

**Comment by inktomi** [comment]
This was actually because of a very old gradle-profiler version in use by mistake. Sorry and have a great day!
