### ISSUE TITLE
Daemon re-used although --no-daemon requested

### ISSUE THREAD

**Issue by gabrielfeo** [gradle/gradle-profiler#417]
Running a benchmark with `--no-daemon` and `gradle-args` containing `--configuration-cache --dry-run` causes the daemon to be re-used for some reason. Profiler is helpful enough to report this, but no idea what causes it. I created a sample project with complete logs: [gabrielfeo/gradle-profiler-no-daemon-issue-sample](https://github.com/gabrielfeo/gradle-profiler-no-daemon-issue-sample)

```
...
* Stopping daemons
Running command /builds/ifood/consumer/mobile/consumer-android/.gradle-home/wrapper/dists/gradle-7.3.3-all/4295vidhdd9hd3gbjyw1xqxpo/gradle-7.3.3/bin/gradle --stop --gradle-user-home /builds/ifood/consumer/mobile/consumer-android/.gradle-home
No Gradle daemons are running.
* Running warm-up build #1
...
BUILD SUCCESSFUL in 58s
Used daemon with pid 1603
...
* Stopping daemons
Running command /builds/ifood/consumer/mobile/consumer-android/.gradle-home/wrapper/dists/gradle-7.3.3-all/4295vidhdd9hd3gbjyw1xqxpo/gradle-7.3.3/bin/gradle --stop --gradle-user-home /builds/ifood/consumer/mobile/consumer-android/.gradle-home
Stopping Daemon(s)
1 Daemon stopped
* Running measured build #1
...
BUILD SUCCESSFUL in 6s
Used daemon with pid 1603
...
* Stopping daemons
Running command /builds/ifood/consumer/mobile/consumer-android/.gradle-home/wrapper/dists/gradle-7.3.3-all/4295vidhdd9hd3gbjyw1xqxpo/gradle-7.3.3/bin/gradle --stop --gradle-user-home /builds/ifood/consumer/mobile/consumer-android/.gradle-home
Stopping Daemon(s)
1 Daemon stopped
* Running measured build #2
...
BUILD SUCCESSFUL in 6s
Used daemon with pid 1603
* Stopping daemons
Running command /builds/ifood/consumer/mobile/consumer-android/.gradle-home/wrapper/dists/gradle-7.3.3-all/4295vidhdd9hd3gbjyw1xqxpo/gradle-7.3.3/bin/gradle --stop --gradle-user-home /builds/ifood/consumer/mobile/consumer-android/.gradle-home
Stopping Daemon(s)
1 Daemon stopped
java.lang.RuntimeException: Gradle daemon was reused but should not be reused.
	at org.gradle.profiler.GradleScenarioInvoker.checkPid(GradleScenarioInvoker.java:195)
	at org.gradle.profiler.GradleScenarioInvoker.run(GradleScenarioInvoker.java:154)
	at org.gradle.profiler.GradleScenarioInvoker.run(GradleScenarioInvoker.java:22)
	at org.gradle.profiler.Main.invoke(Main.java:126)
	at org.gradle.profiler.Main.run(Main.java:86)
	at org.gradle.profiler.Main.main(Main.java:25)

```

PS: I was benchmarking `--configuration-cache` with `--no-daemon` by mistake, I don't see a use case for this. I just thought it was worth reporting.

**Comment by kenyee** [comment]
I hit this as well using latest from master...looks like there's a way to turn this polling off:
https://github.com/gradle/gradle-profiler/issues/63

**Comment by ov7a** [comment]
Sorry for the late reply.

I've reopened
* #63

Closing this issue as its duplicate.
