### ISSUE TITLE
Improve mutator+invoker incompatibility message

### ISSUE THREAD

**Issue by gabrielfeo** [gradle/gradle-profiler#420]
## Problem 

Given a scenario with a mutator that is incompatible with the current `BuildInvoker`, `clear-build-cache-before = "BUILD"` in my case when running with the default `ToolingApi` invoker, Profiler will fail with a message that helps the user understand what can't be done, but isn't clear on the real alternatives. My user flow to benchmark my scenario was as follows:

```hocon
with-clean-build-cache {
  tasks = ["help"]
  clear-build-cache-before = "BUILD"
}
```

<details>
<summary>Used tooling API invoker (<code>gradle-profiler</code>)</summary>

```
$ gradle-profiler --benchmark --gradle-user-home ~/.gradle/ --scenario-file example-scenarios.conf with-clean-build-cache

...

* Inspecting the build using its default Gradle version

* Stopping daemons
java.lang.IllegalStateException: Scenario 'with-clean-build-cache' is invalid: ClearBuildCacheMutator(BUILD) is not allowed to be executed between builds with invoker Tooling API
	at org.gradle.profiler.ScenarioDefinition.validate(ScenarioDefinition.java:38)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:304)
	at org.gradle.profiler.ScenarioLoader.doLoadScenarios(ScenarioLoader.java:175)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:156)
	at org.gradle.profiler.Main.run(Main.java:56)
	at org.gradle.profiler.Main.main(Main.java:25)
Caused by: java.lang.IllegalStateException: ClearBuildCacheMutator(BUILD) is not allowed to be executed between builds with invoker Tooling API
	at org.gradle.profiler.mutations.AbstractCleanupMutator.validate(AbstractCleanupMutator.java:27)
	at org.gradle.profiler.ScenarioDefinition.validate(ScenarioDefinition.java:36)
	... 6 more
```

</details>

> Fine, I can run with `--cli`. [From the README, I understand it's the only alternative](https://github.com/gradle/gradle-profiler/blob/master/README.md?plain=1#L205)

<details>
<summary>Tried CLI invoker instead (<code>gradle-profiler --cli</code>)</summary>

```
$ gradle-profiler --benchmark --gradle-user-home ~/.gradle/ --scenario-file example-scenarios.conf with-clean-build-cache --cli

* Writing results to /Users/gabrieldeaguiarfeo/Projects/gradle-profiler-incompatible-invoker-msg-improvement/profile-out-2

* Settings
Project dir: /Users/gabrieldeaguiarfeo/Projects/gradle-profiler-incompatible-invoker-msg-improvement
Output dir: /Users/gabrieldeaguiarfeo/Projects/gradle-profiler-incompatible-invoker-msg-improvement/profile-out-2
Profiler: none
Benchmark: true
Versions: []
Gradle User Home: /Users/gabrieldeaguiarfeo/.gradle
Targets: [with-clean-build-cache]

* Inspecting the build using its default Gradle version

* Stopping daemons
java.lang.IllegalStateException: Scenario 'with-clean-build-cache' is invalid: ClearBuildCacheMutator(BUILD) is not allowed to be executed between builds with invoker `gradle` command
	at org.gradle.profiler.ScenarioDefinition.validate(ScenarioDefinition.java:38)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:304)
	at org.gradle.profiler.ScenarioLoader.doLoadScenarios(ScenarioLoader.java:175)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:156)
	at org.gradle.profiler.Main.run(Main.java:56)
	at org.gradle.profiler.Main.main(Main.java:25)
Caused by: java.lang.IllegalStateException: ClearBuildCacheMutator(BUILD) is not allowed to be executed between builds with invoker `gradle` command
	at org.gradle.profiler.mutations.AbstractCleanupMutator.validate(AbstractCleanupMutator.java:27)
	at org.gradle.profiler.ScenarioDefinition.validate(ScenarioDefinition.java:36)
	... 6 more
```

</details>

> Confusion. Aren't these the _only_ invokers?

After looking into profiler source code, I discovered that there are more invokers depending on args other than `--cli`. Also, that the one adequate for my use case (I needed to clear cache before builds) was `CliNoDaemon`, by looking at what [this method](/src/main/java/org/gradle/profiler/GradleBuildInvoker.java#L29) would return for it.

<details>
<summary>Finally tried CLI invoker with no (or cold) daemon (<code>gradle-profiler --cli --no-daemon</code>)</summary>

```
$ gradle-profiler --benchmark --gradle-user-home ~/.gradle/ --scenario-file example-scenarios.conf with-clean-build-cache --cli --no-daemon

* Writing results to /Users/gabrieldeaguiarfeo/Projects/gradle-profiler-incompatible-invoker-msg-improvement/profile-out-3

* Settings
Project dir: /Users/gabrieldeaguiarfeo/Projects/gradle-profiler-incompatible-invoker-msg-improvement
Output dir: /Users/gabrieldeaguiarfeo/Projects/gradle-profiler-incompatible-invoker-msg-improvement/profile-out-3
Profiler: none
Benchmark: true
Versions: []
Gradle User Home: /Users/gabrieldeaguiarfeo/.gradle
Targets: [with-clean-build-cache]

* Inspecting the build using its default Gradle version
^C (I interrupted it because it doesn't fail)
```

</details>

## Suggestion

My suggestion is to change the message to something like this:
```
ClearBuildCacheMutator(BUILD) is not allowed to be executed between builds with invoker `gradle` command.
Allowed invokers:  ["`gradle` command with --no-daemon`", "`gradle` command with cold daemon"].
```

I intend to open a PR if you're OK with the general idea.

**Comment by kenyee** [comment]
What's additionally weird is that running gradle-profiler with:
```
gradle-profiler --cli --no-daemon
```
Causes gradle to run w/o a daemon at all...i.e., if you have a gradle plugin/task that tries to look up the gradle daemon in the gradle service registry, it won't find it.  This seems like incorrect behavior because if you manually run "./gradlew --no-daemon", it will run the build with a daemon but shut down the daemon at the end.

**Comment by kenyee** [comment]
https://github.com/gradle/gradle-profiler/blob/cd4881ceb74b7c2c14f60c58c18d2239157f172b/src/test/groovy/org/gradle/profiler/ProfilerIntegrationTest.groovy#L1303

Saw this in the unit test code...
looks like you can set daemon=cold as well

**Comment by tresat** [comment]
Sorry for the late reply.

This feature request is in the backlog of the relevant team and is prioritized by them.

***

This could also use better documentation.
