### ISSUE TITLE
Bazel benchmark: command not found error

### ISSUE THREAD

**Issue by jeraldsun** [gradle/gradle-profiler#434]
I was using the Bazel benchamrk and got the following error:
```
java.lang.RuntimeException: Could not run command /usr/local/bin/bazel build //assemble/doc-sdk-demo:doc-sdk-demo
Output:
======
Command 'build //assemble/doc-sdk-demo:doc-sdk-demo' not found. Try 'bazel help'.
======
	at org.gradle.profiler.CommandExec$RunHandle.waitForSuccess(CommandExec.java:207)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:32)
	at org.gradle.profiler.BuildToolCommandLineInvoker$1.run(BuildToolCommandLineInvoker.java:49)
	at org.gradle.profiler.RunBuildStepAction.run(RunBuildStepAction.java:29)
	at org.gradle.profiler.ScenarioInvoker.runMeasured(ScenarioInvoker.java:28)
	at org.gradle.profiler.BuildToolCommandLineInvoker.doRun(BuildToolCommandLineInvoker.java:24)
	at org.gradle.profiler.BazelScenarioInvoker.run(BazelScenarioInvoker.java:18)
	at org.gradle.profiler.BazelScenarioInvoker.run(BazelScenarioInvoker.java:9)
	at org.gradle.profiler.Main.invoke(Main.java:126)
	at org.gradle.profiler.Main.run(Main.java:78)
	at org.gradle.profiler.Main.main(Main.java:25)
```
My scenario file looks like this:
```
incremental_build {
    title = "Gradle vs Bazel Incremental Build"
    tasks = ["assemble:doc-sdk-demo:assembleDebug"]
    system-properties {
        "RJE_VERBOSE" = "true",
        "COURSIER_OPTS" = "-Xms1g -Xmx16g"
    }
    bazel {
        targets = ["build" "//assemble/doc-sdk-demo:doc-sdk-demo"]
        home = "/usr/local"
    }
    warm-ups = 2
    iterations = 5
    apply-non-abi-change-to = ["business/docs/edit-component/src/main/java/com/bytedance/ee/bear/doc/toolbar/DocToolbar.java", "business/framework/biz-net/src/main/java/com/bytedance/ee/bear/contract/ConnectionServiceImp.java","business/framework/file-selector/src/main/java/com/bytedance/ee/bear/fileselector/FileSelectFragment.kt"]
}
```
But I can run `/usr/local/bin/bazel build //assemble/doc-sdk-demo:doc-sdk-demo` inside the project's workspace successfully.
Is anything wrong with my scenario?

**Comment by tresat** [comment]
Your issue appears to be a question about how to use Gradle Profiler. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

***

You should put a comma here: `targets = ["build", "//assemble/doc-sdk-demo:doc-sdk-demo"]`.
