### ISSUE TITLE
Android Studio sync benchmark loses communication with Electric Eel/canary version

### ISSUE THREAD

**Issue by kenyee** [gradle/gradle-profiler#443]
AS sync doesn't seem to work properly w/ EE.  It starts up and claims it's waiting for sync and doesn't wait long enough.  It brings up a sandbox version of AS and then says it stopped and gets stuck on the "stopped." line for a while until it says the plugin lost communication:

```
* Using command line: [/Applications/Android Studio Electric Eel.app/Contents/jbr/Contents/Home/bin/java, -cp, /Applications/Android Studio Electric Eel.app/Contents/lib/util.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/app.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/3rd-party-rt.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/jna.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/platform-statistics-devkit.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/jps-model.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/rd-core.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/rd-framework.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/stats.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/protobuf.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/external-system-rt.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/forms_rt.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/intellij-test-discovery.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/rd-swing.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/annotations.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/groovy.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/annotations-java5.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/byte-buddy-agent.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/error-prone-annotations.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/externalProcess-rt.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/grpc-netty-shaded.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/idea_rt.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/intellij-coverage-agent-1.0.656.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/junit.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/junit4.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/lz4-java.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/platform-objectSerializer-annotations.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/pty4j.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/rd-text.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/resources.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/util_rt.jar:/Applications
/Android Studio Electric Eel.app/Contents/lib/winp.jar:/Applications/Android Studio Electric Eel.app/Contents/lib/ant/lib/ant.jar, -Didea.strict.classpath=true, -Dgradle.profiler.startup.port=58161, -Dgradle.profiler.port=58162, -Didea.config.path=/Users/keny/workspace/twitter-android/build/profiler/TfA/studio-sandbox/config, -Didea.log.path=/Users/keny/workspace/twitter-android/build/profiler/TfA/studio-sandbox/logs, -Didea.jre.check=true, -Didea.system.path=/Users/keny/workspace/twitter-android/build/profiler/TfA/studio-sandbox/system, -Didea.paths.selector=AndroidStudioPreview2022.1, -Didea.vendor.name=Google, -Djava.system.class.loader=com.intellij.util.lang.PathClassLoader, -Didea.plugins.path=/Users/keny/workspace/twitter-android/build/profiler/TfA/studio-sandbox/plugins, -Didea.trust.all.projects=true, -Dsplash=true, -Didea.platform.prefix=AndroidStudio, -Didea.executable=studio, -Didea.home.path=/Applications/Android Studio Electric Eel.app/Contents, -javaagent:/private/var/folders/3x/2b22lrdx3fzdcxpf9nx6cm6c0000gp/T/studio-agent8381676831750327625.jar=58163,/private/var/folders/3x/2b22lrdx3fzdcxpf9nx6cm6c0000gp/T/instrumentation-support17516474402696420456.jar, --add-exports, java.base/jdk.internal.misc=ALL-UNNAMED, -Xbootclasspath/a:/private/var/folders/3x/2b22lrdx3fzdcxpf9nx6cm6c0000gp/T/asm15664558713547433238.jar:/private/var/folders/3x/2b22lrdx3fzdcxpf9nx6cm6c0000gp/T/client-protocol8918710905363533852.jar, -Xms4g, -Xmx16g, com.intellij.idea.Main, /Users/keny/workspace/twitter-android/.]

* Running sync in Android Studio...
* Sent sync request
* Sync has started, waiting for it to complete...
* Stopping Android Studio....
* Android Studio stopped.

* Stopping daemons
java.lang.IllegalStateException: Connection to plugin has closed.
	at org.gradle.profiler.client.protocol.serialization.MessageProtocolHandler.receive(MessageProtocolHandler.java:61)
	at org.gradle.profiler.client.protocol.serialization.MessageProtocolHandler.receive(MessageProtocolHandler.java:48)
	at org.gradle.profiler.client.protocol.ServerConnection.receiveSyncRequestCompleted(ServerConnection.java:42)
	at org.gradle.profiler.studio.StudioGradleClient.waitForSyncToFinish(StudioGradleClient.java:112)
	at org.gradle.profiler.studio.StudioGradleClient.lambda$sync$1(StudioGradleClient.java:88)
	at org.gradle.profiler.studio.process.StudioProcessController.run(StudioProcessController.java:64)
	at org.gradle.profiler.studio.process.StudioProcessController.run(StudioProcessController.java:43)
	at org.gradle.profiler.studio.StudioGradleClient.sync(StudioGradleClient.java:84)
	at org.gradle.profiler.AndroidStudioSyncAction.run(AndroidStudioSyncAction.java:33)
	at org.gradle.profiler.BuildUnderTestInvoker$InvokeAndMeasureAction.run(BuildUnderTestInvoker.java:61)
	at org.gradle.profiler.BuildUnderTestInvoker$InvokeAndMeasureAction.run(BuildUnderTestInvoker.java:41)
	at org.gradle.profiler.RunBuildStepAction.run(RunBuildStepAction.java:29)
	at org.gradle.profiler.ScenarioInvoker.runMeasured(ScenarioInvoker.java:28)
	at org.gradle.profiler.GradleScenarioInvoker.run(GradleScenarioInvoker.java:116)
	at org.gradle.profiler.studio.invoker.StudioGradleScenarioInvoker.run(StudioGradleScenarioInvoker.java:63)
	at org.gradle.profiler.studio.invoker.StudioGradleScenarioInvoker.run(StudioGradleScenarioInvoker.java:19)
	at org.gradle.profiler.Main.invoke(Main.java:126)
	at org.gradle.profiler.Main.run(Main.java:84)
	at org.gradle.profiler.Main.main(Main.java:25)
```

The IDEA log doesn't have any clues:
```
2022-08-24 17:56:23,621 [      2]   INFO - #c.i.i.StartupUtil - ------------------------------------------------------ IDE STARTED ------------------------------------------------------
2022-08-24 17:56:23,642 [     23]   INFO - #c.i.u.EnvironmentUtil - loading shell env is skipped: IDE has been launched from a terminal (SHLVL=1)
2022-08-24 17:56:23,656 [     37]   INFO - #c.i.i.p.PluginManager - Ignoring cached broken plugins file from an earlier IDE build (AI-221.5921.22.2211.__BUILD_NUMBER__)
2022-08-24 17:56:23,733 [    114]   INFO - #c.i.i.p.PluginManager - Plugin PluginDescriptor(name=Groovy, id=org.intellij.groovy, descriptorPath=plugin.xml, path=/Applications/Android Studio Electric Eel.app/Contents/plugins/Groovy, version=221.5921.22.2211.8881706, package=org.jetbrains.plugins.groovy, isBundled=true) misses optional descriptor duplicates-groovy.xml
2022-08-24 17:56:23,734 [    115]   INFO - #c.i.i.p.PluginManager - Plugin PluginDescriptor(name=Groovy, id=org.intellij.groovy, descriptorPath=plugin.xml, path=/Applications/Android Studio Electric Eel.app/Contents/plugins/Groovy, version=221.5921.22.2211.8881706, package=org.jetbrains.plugins.groovy, isBundled=true) misses optional descriptor duplicates-detection-groovy.xml
2022-08-24 17:56:23,789 [    170]   INFO - #c.i.i.p.PluginManager - Module kotlin.features-trainer is not enabled because dependency training is not available
Module kotlin.grazie is not enabled because dependency tanvd.grazi is not available
```

Anything else I can look at to help debug this?

**Comment by asodja** [comment]
What version of gradle-profiler did you use? Note that gradle-profiler 0.18.0 doesn't support  Electric Eel. If you want to use Electric Eel, you have to build gradle-profiler from master. 

You can do that with:
`./gradlew installDist`
and then you can run it with (case when you are in gradle-profiler dir):
`./build/install/gradle-profiler/bin/gradle-profiler`

**Comment by kenyee** [comment]
ahh, I'm using 0.18.0.  
I should have checked the closed issues:
https://github.com/gradle/gradle-profiler/issues/437

Closing this as a dup.

**Comment by kenyee** [comment]
Any idea when 0.19.0 will be released?   Seems like it has fixes for chipmunk/dolphin as well which might explain why they didn't work for me either :-)

**Comment by kenyee** [comment]
confirmed current master works w/ Electric Eel (alpha), Dolphin (beta), Chipmunk (stable)...actually causes AS to sync instead of saying "AS stopped" and then trying to continue :-)

Also the CSV report file looks pretty broken/weird (see #317)...probably should be fixed before next release if possible.
