### ISSUE TITLE
Incompatibility with Android Studio Electric Eel Canary 10+

### ISSUE THREAD

**Issue by mikejuyoon** [gradle/gradle-profiler#450]
When running Gradle Profiler with AS Electric Eel Canary 10+ (including Beta1) we get the following error:
```
2022-08-31 19:59:07,675 [   7587] SEVERE - #c.i.o.a.i.ApplicationImpl - GRADLE_SYNC_TOPIC
java.lang.NoSuchFieldError: GRADLE_SYNC_TOPIC
        at org.gradle.profiler.studio.plugin.system.AndroidStudioSystemHelper.doGradleSync(AndroidStudioSystemHelper.java:35)
        at org.gradle.profiler.studio.plugin.client.GradleProfilerClient.startManualSync(GradleProfilerClient.java:92)
        at org.gradle.profiler.studio.plugin.client.GradleProfilerClient.getStartupSyncResult(GradleProfilerClient.java:104)
        at org.gradle.profiler.studio.plugin.client.GradleProfilerClient.handleSyncRequest(GradleProfilerClient.java:86)
        at org.gradle.profiler.studio.plugin.client.GradleProfilerClient.handleGradleProfilerRequest(GradleProfilerClient.java:63)
        at org.gradle.profiler.studio.plugin.client.GradleProfilerClient.listenForSyncRequests(GradleProfilerClient.java:46)
        at org.gradle.profiler.studio.plugin.GradleProfilerProjectManagerListener.listenForSyncRequests(GradleProfilerProjectManagerListener.java:47)
        at org.gradle.profiler.studio.plugin.GradleProfilerProjectManagerListener.lambda$projectOpened$0(GradleProfilerProjectManagerListener.java:36)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-08-31 19:59:07,677 [   7589] SEVERE - #c.i.o.a.i.ApplicationImpl - Android Studio Electric Eel | 2022.1.1 Canary 10  Build #AI-221.6008.13.2211.8963757
2022-08-31 19:59:07,679 [   7591] SEVERE - #c.i.o.a.i.ApplicationImpl - JDK: 11.0.15; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-08-31 19:59:07,679 [   7591] SEVERE - #c.i.o.a.i.ApplicationImpl - OS: Linux
2022-08-31 19:59:07,680 [   7592] SEVERE - #c.i.o.a.i.ApplicationImpl - Plugin to blame: Gradle Profiler IntelliJ/Android Studio Plugin version: 0.19.0-alpha01
```

It appears that  Gradle Profiler is listening on this topic: `GradleSyncState.GRADLE_SYNC_TOPIC` https://github.com/gradle/gradle-profiler/blob/fbfc92da4d5b2568c108a8b98cf513639dcdc03b/subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/system/AndroidStudioSystemHelper.java#L35 but the AS code has recently in a way that Sync events are emitted in a different manner

**Comment by mikejuyoon** [comment]
thanks for the fix @asodja !!
