### ISSUE TITLE
Using `--profile yourkit` in Windows build failed with java.lang.NullPointerException

### ISSUE THREAD

**Issue by saulsq** [gradle/gradle-profiler#456]
### Environment
gradle-profiler version: 0.19.0
YourKit version: 2022.9

**Crash log**
```
java.lang.NullPointerException
        at org.gradle.profiler.yourkit.YourKitJvmArgsCalculator.calculateJvmArgs(YourKitJvmArgsCalculator.java:33)
        at org.gradle.profiler.GradleScenarioInvoker.run(GradleScenarioInvoker.java:87)
        at org.gradle.profiler.GradleScenarioInvoker.run(GradleScenarioInvoker.java:22)
        at org.gradle.profiler.Main.invoke(Main.java:126)
        at org.gradle.profiler.Main.run(Main.java:86)
        at org.gradle.profiler.Main.main(Main.java:25)
```

### Root cause
In YourKit HOME dir
yjpagent.dll exist in `bin/windows-x86-64/`

but in gradle-profiler, the path still was `bin/win64/`
https://github.com/gradle/gradle-profiler/blob/master/src/main/java/org/gradle/profiler/yourkit/YourKit.java#L41

So the `findJniLib()` result will be null

### Temporary solution
copy `bin/windows-x86-64` and rename to `bin/win64`

**Comment by saulsq** [comment]
> Is there any way you could test that #457 fixes it?
> 
> You can test that by:
> 
> 1. `git clone git@github.com:gradle/gradle-profiler.git`
> 2. `git checkout asodja/yourkit-fix`
> 3. `./gradlew installDist`
> 
> And then gradle-profiler would be available in `./build/install/gradle-profiler/bin/gradle-profiler`.

Hi @asodja

**Comment by asodja** [comment]
Thanks for verifying the fix!
