### ISSUE TITLE
Password protected gradle distribution url

### ISSUE THREAD

**Issue by NikitaZhelonkin** [gradle/gradle-profiler#465]
Hello! We have password protected gradle wrapper distribution url. 
Credential are provided in `~/.gradle/gradle.properties`:
  
 ```
systemProp.gradle.wrapperUser=login
systemProp.gradle.wrapperPassword=token
```

Also tried to set creds via GRADLE_OPTS environment variable
`export GRADLE_OPTS=-Dgradle.wrapperUser=login -Dgradle.wrapperPassword=token`

When run gradle profiler got an exception:
 ````
org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from '<URL HERE>'.
        at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:135)
        at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:41)
        at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:44)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:160)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:142)
        at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecuto
 ````

**Comment by asodja** [comment]
Does it work, if you set system property via [command line option](https://github.com/gradle/gradle-profiler#command-line-options)?
```
-D<key>=<value>: Defines a system property when running the build, overriding the default for the build.
```
