### ISSUE TITLE
ConnectionException in profiling

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle-profiler#47]
```
$ ./build/install/gradle-profiler/bin/gradle-profiler --warmups 0 --no-daemon --profile jprofiler --project-dir /Users/zhb/Projects/gradle/subprojects/performance/build/largeJavaMultiProjectCurrent --gradle-user-home /Users/zhb/Projects/gradle/subprojects/performance/build/largeJavaMultiProjectCurrent/gradle-user-home --gradle-version '/Users/zhb/Projects/gradle/subprojects/performance/build/integ test' tasks

* Writing results to /Users/zhb/Projects/gradle-profiler/profile-out-8

* Settings
Project dir: /Users/zhb/Projects/gradle/subprojects/performance/build/largeJavaMultiProjectCurrent
Output dir: profile-out-8
Profiler: JProfiler
Benchmark: false
Versions: [/Users/zhb/Projects/gradle/subprojects/performance/build/integ test]
Gradle User Home: /Users/zhb/Projects/gradle/subprojects/performance/build/largeJavaMultiProjectCurrent/gradle-user-home
Targets: [tasks]

* Inspecting Gradle version '/Users/zhb/Projects/gradle/subprojects/performance/build/integ test'

* Stopping daemons

* Scenarios
Scenario: using Gradle 4.4-20170906000000+0800
  Gradle version: 4.4-20170906000000+0800 (/Users/zhb/Projects/gradle/subprojects/performance/build/integ test)
  Run using: NoDaemon
  Cleanup Tasks: []
  Tasks: [tasks]
  Gradle args: []
  Build changes: none
  Warm-ups: 0
  Builds: 1

* Running scenario using Gradle 4.4-20170906000000+0800 (scenario 1/1)

* Stopping daemons

* Running warm-up build 1 with tasks [tasks]
Execution time 18179ms

* Starting recording for daemon with pid 4054

* Running build 1 with tasks [tasks]
Exception in thread "JProfiler connector" java.lang.IllegalStateException: Failed to connect to build VM after 5000ms
	at org.gradle.profiler.jprofiler.JProfilerController.tryStartNow(JProfilerController.java:68)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:249)
	at org.gradle.profiler.jprofiler.JProfilerController.ensureConnected(JProfilerController.java:131)
	at org.gradle.profiler.jprofiler.JProfilerController.invoke(JProfilerController.java:158)
	at org.gradle.profiler.jprofiler.JProfilerController.startNow(JProfilerController.java:73)
	at org.gradle.profiler.jprofiler.JProfilerController.tryStartNow(JProfilerController.java:56)
	... 1 more
Caused by: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)]
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
	... 6 more
Caused by: java.rmi.ConnectException: Connection refused to host: localhost; nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
	... 11 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 16 more
Execution time 18868ms

* Stopping recording for daemon with pid 4054

* Stopping daemons
java.lang.NullPointerException
	at org.gradle.profiler.jprofiler.JProfilerController.closeConnection(JProfilerController.java:143)
	at org.gradle.profiler.jprofiler.JProfilerController.stop(JProfilerController.java:111)
	at org.gradle.profiler.Main.runGradleScenario(Main.java:210)
	at org.gradle.profiler.Main.run(Main.java:74)
	at org.gradle.profiler.Main.main(Main.java:24)
```

**Comment by oehme** [comment]
@blindpirate which version of JProfiler are you using?

**Comment by blindpirate** [comment]
`10.0.4`

**Comment by blindpirate** [comment]
I'll try `9.2` because I really feel bad with `10.0.4`. It's extremely slow (profiling/generate snapshot/open snapshot/compare snapshot) and I don't know why.

**Comment by oehme** [comment]
@blindpirate 10 should work and I haven't had any problems with it. Did you get it working or are you still having problems?

**Comment by oehme** [comment]
Closing as there was no further feedback.

**Comment by sutrosoftware** [comment]
I'm seeing this same issue.

**Comment by sutrosoftware** [comment]
...using JProfiler v9.2.1, running on Windows 7.

**Comment by sutrosoftware** [comment]
....with Gradle 4.4.1.
