### ISSUE TITLE
Android Studio sync fails with Android Studio Hedgehog, 2023.1.1 Canary 14

### ISSUE THREAD

**Issue by asodja** [gradle/gradle-profiler#508]
It seems we are using some method that was removed in `2023.1.1.14` or maybe before that. We currently test with `2023.1.1.6` and syncs work with that version.
From logs for `2023.1.1.14`:
```
2023-07-26 13:54:33,932 [   2435] SEVERE - #c.i.i.s.i.StartupManagerImpl - 'void com.android.tools.idea.gradle.project.GradleProjectInfo.setSkipStartupActivity(boolean)'
java.lang.NoSuchMethodError: 'void com.android.tools.idea.gradle.project.GradleProjectInfo.setSkipStartupActivity(boolean)'
	at org.gradle.profiler.studio.plugin.GradleProfilerStartupActivity.runActivity(GradleProfilerStartupActivity.java:40)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:328)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$2$1.invoke(StartupManagerImpl.kt:269)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$2$1.invoke(StartupManagerImpl.kt:268)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:268)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:178)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by asodja** [comment]
It looks like it works with Hedgehog 2023.1.1.22 and Iguana 2023.2.1.7, see https://github.com/gradle/gradle-profiler/pull/514.
