### ISSUE TITLE
Android Studio sync benchmark times out on larger projects

### ISSUE THREAD

**Issue by TadeasKriz** [gradle/gradle-profiler#525]
We're seeing issue where the benchmark fails with: 
```
java.lang.IllegalStateException: Timeout waiting for incoming connection from plugin.
	at org.gradle.profiler.client.protocol.Server.waitForIncoming(Server.java:50)
	at org.gradle.profiler.studio.process.StudioProcess.<init>(StudioProcess.java:39)
	at org.gradle.profiler.studio.process.StudioProcessController.maybeStartProcess(StudioProcessController.java:76)
	at org.gradle.profiler.studio.process.StudioProcessController.run(StudioProcessController.java:43)
	at org.gradle.profiler.studio.StudioGradleClient.sync(StudioGradleClient.java:78)
	at org.gradle.profiler.studio.AndroidStudioSyncAction.run(AndroidStudioSyncAction.java:36)
	at org.gradle.profiler.gradle.BuildUnderTestInvoker$InvokeAndMeasureAction.run(BuildUnderTestInvoker.java:71)
	at org.gradle.profiler.gradle.BuildUnderTestInvoker$InvokeAndMeasureAction.run(BuildUnderTestInvoker.java:51)
	at org.gradle.profiler.RunBuildStepAction.run(RunBuildStepAction.java:29)
	at org.gradle.profiler.ScenarioInvoker.runMeasured(ScenarioInvoker.java:28)
	at org.gradle.profiler.gradle.GradleScenarioInvoker.run(GradleScenarioInvoker.java:121)
	at org.gradle.profiler.studio.invoker.StudioGradleScenarioInvoker.run(StudioGradleScenarioInvoker.java:63)
	at org.gradle.profiler.studio.invoker.StudioGradleScenarioInvoker.run(StudioGradleScenarioInvoker.java:19)
	at org.gradle.profiler.Main.invoke(Main.java:140)
	at org.gradle.profiler.Main.run(Main.java:98)
	at org.gradle.profiler.Main.main(Main.java:37)
```

From my debugging it seems the issue is caused by indexing taking too long and because of that the [GradleProfilerStartupActivity#runActivity](https://github.com/gradle/gradle-profiler/blob/master/subprojects/studio-plugin/src/main/java/org/gradle/profiler/studio/plugin/GradleProfilerStartupActivity.java#L41C1-L42C1) isn't called in before Gradle Profiler times out.

**Comment by asodja** [comment]
That probably means that IDE was not started correctly.

Which version of AS are using? There is a report that gradle-profiler doesn work with Jellyfish, see https://github.com/gradle/gradle-profiler/issues/526

**Comment by kirillzh** [comment]
Seeing this on Android Studio 2023.3.1.18 with Gradle 8.7. 

Tried using Gradle Profiler 0.21.0-alpha-4 which is supposed to include the [fix](https://github.com/gradle/gradle-profiler/pull/532) for https://github.com/gradle/gradle-profiler/issues/526, but seeing same error.

**Comment by gabrielfeo** [comment]
I also encountered this error. Profiler output was the same and in Android Studio it was:

```
Timeout waiting to receive class org.gradle.profiler.client.protocol.messages.StudioAgentConnectionParameters.
```

It seems fixed [on the latest source](https://github.com/gradle/gradle-profiler?tab=readme-ov-file#build-from-source). Working properly with Jellyfish and Koala 2024.1.1 on a large build (480 subprojects).

**Comment by tresat** [comment]
Sorry for the late reply.

Given the last comment, we're assuming this was fixed.

If this is not the case, please re-open this issue, providing all relevant information to reproduce the problem.
