### ISSUE TITLE
Crash with android-studio-sync in 0.21.17-alpha*

### ISSUE THREAD

**Issue by handstandsam** [gradle/gradle-profiler#549]
`0.21.17+` versions no longer allow Android Studio Sync Profiling with Android Studio Iguana on Mac (M1) with Ventura.  The last working release was `0.21.0-alpha-4` that supported Android Studio Sync benchmarking. Confirmed (via local testing between versions of `gradle-profiler`). 

All versions tried are from the binary `.zip` files hosted here: https://repo1.maven.org/maven2/org/gradle/profiler/gradle-profiler/

Crash:
```
* Stopping daemons
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at org.gradle.profiler.ScenarioLoader.newStudioGradleScenarioDefinition(ScenarioLoader.java:322)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:303)
	at org.gradle.profiler.ScenarioLoader.doLoadScenarios(ScenarioLoader.java:181)
	at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:162)
	at org.gradle.profiler.Main.run(Main.java:68)
	at org.gradle.profiler.Main.main(Main.java:37)
```

To replicate, use:
```
./gradle-profiler --benchmark --scenario-file android-studio.scenarios studio_sync --studio-install-dir "${YOUR_PATH_HERE}/Iguana/Android Studio.app"
```

android-studio.scenarios
```
studio_sync {
    title = "Android Studio Sync"
    android-studio-sync {
    }
    warm-ups = 1
    iterations = 1
 }
 ```

**Comment by joshfriend** [comment]
This is the commit that breaks the sync scenarios: https://github.com/gradle/gradle-profiler/commit/343774faca54f636d78641b255364b55f9bbd47c

It appears that the `0.21.17` versions are from [an un-merged branch](https://github.com/gradle/gradle-profiler/compare/ide-provisioning-java17) and are possibly testing versions?

**Comment by asodja** [comment]
Yes, this was a mistake on our end. Please ignore that version and use only `0.21.0-alpha-*` versions.

**Comment by joshfriend** [comment]
>  next stable will be 0.21.0

That will sort lower than 0.21.17 and any alpha variants. If you want to be sure these bad versions wont cause any problems for tools like [Renovate](https://github.com/renovatebot/renovate), you might have to skip 0.21.0 stable entirely and go straight to 0.22.0. Or release as 0.21.18 which seems more confusing.

**Comment by ov7a** [comment]
There was a 0.23 release already, considering this issue as fixed in 0.22.0
