### ISSUE TITLE
Using Gradle 8.8 fails `android-studio-sync` with `invalid type code: 0C`

### ISSUE THREAD

**Issue by kirillzh** [gradle/gradle-profiler#559]
Gradle Profiler 0.20.0
Gradle 8.8
Android Studio 2023.2.1.15
Host machine: macOS 14.5

Logs
```
GRADLE_PROFILER_OPTS=-Dstudio.tests.headless=true ../../bin/gradle-profiler --benchmark --project-dir ../.. --scenario-file profiler.scenarios --output-dir _build/profile-out --gradle-user-home _build/gradle-user-home --studio-install-dir "_build/Android Studio Preview.app" sync_android_studio

* Writing results to /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out

* Settings
Project dir: /Users/runner/work/wallet/wallet/app/gradle/benchmarks/../..
Output dir: /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out
Profiler: none
Benchmark: true
Versions: []
Gradle User Home: /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/gradle-user-home
Targets: [sync_android_studio]

* Inspecting the build using its default Gradle version
Downloading https://services.gradle.org/distributions/gradle-8.7-all.zip
......................................................................................................................................................................................................................

* Stopping daemons

* Scenarios
Scenario: Android Studio Sync using Gradle 8.7
  Gradle 8.7 (/Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/gradle-user-home/wrapper/dists/gradle-8.7-all/aan3ydargesu18aqyqjwhr3pc/gradle-8.7)
  Run using: Android Studio
  Run: Android Studio sync
  Cleanup: do nothing
  Gradle args: []
  Build changes: []
  Warm-ups: 6
  Builds: 10

* Running scenario Android Studio Sync using Gradle 8.7 (scenario 1/1)

* Stopping daemons

* Running warm-up build #1


* Starting Android Studio at /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/Android Studio Preview.app
* Start command: /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/Android Studio Preview.app/Contents/MacOS/studio
* Additional JVM args:
  -javaagent:/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/studio-agent1[24](https://github.com/squareup/wallet/actions/runs/9328648814/job/25680061672#step:7:25)64825348133204081.jar=49335,/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/instrumentation-support2766219165969696140.jar
  --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED
  -Xbootclasspath/a:/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/asm17249195783107535969.jar:/private/var/folders/lr/439_fwvd3m76p9vy50d57kcc0000gn/T/client-protocol16516[26](https://github.com/squareup/wallet/actions/runs/9328648814/job/25680061672#step:7:27)5336686507289.jar
  -Xmx8192m
  -Didea.gradle.distributionType=BUNDLED
  -Dgradle.profiler.startup.port=49333
  -Dgradle.profiler.port=49334
  -Didea.plugins.path=/Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/studio-sandbox/plugins
  -Didea.config.path=/Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/studio-sandbox/config
  -Didea.log.path=/Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/studio-sandbox/logs
  -Djava.awt.headless=true
  -Didea.trust.all.projects=true
  -Didea.system.path=/Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/studio-sandbox/system
* Additional JVM args can be found at: /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/studio-sandbox/jvmArgs/idea.vmoptions
* Android Studio logs can be found at: /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/studio-sandbox/logs/idea.log
* Using command line: /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/Android Studio Preview.app/Contents/MacOS/studio headless-starter /Users/runner/work/wallet/wallet/app/gradle/benchmarks/../..

* Running sync in Android Studio...
* Sent sync request
* Sync has started, waiting for it to complete...
* Gradle invocation 1 has started, waiting for it to complete...
* Gradle invocation 1 has completed in: 1764294ms
* Full Gradle execution time: 1764294ms
* Full IDE execution time: 4494ms
* Full sync has completed in: 1768788ms and it FAILED
* Stopping Android Studio....
* Android Studio stopped.

* Stopping daemons
java.lang.IllegalStateException: Gradle sync has failed with error message: 'Cause: invalid type code: 0C'. Full Android Studio logs can be found in: '/Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/studio-sandbox/logs/idea.log'.
	at org.gradle.profiler.studio.StudioGradleClient.maybeThrownExceptionOnSyncFailure(StudioGradleClient.java:95)
	at org.gradle.profiler.studio.StudioGradleClient.lambda$sync$1(StudioGradleClient.java:88)
	at org.gradle.profiler.studio.process.StudioProcessController.run(StudioProcessController.java:64)
	at org.gradle.profiler.studio.process.StudioProcessController.run(StudioProcessController.java:43)
	at org.gradle.profiler.studio.StudioGradleClient.sync(StudioGradleClient.java:78)
	at org.gradle.profiler.studio.AndroidStudioSyncAction.run(AndroidStudioSyncAction.java:36)
	at org.gradle.profiler.gradle.BuildUnderTestInvoker$InvokeAndMeasureAction.run(BuildUnderTestInvoker.java:71)
	at org.gradle.profiler.gradle.BuildUnderTestInvoker$InvokeAndMeasureAction.run(BuildUnderTestInvoker.java:51)
	at org.gradle.profiler.RunBuildStepAction.run(RunBuildStepAction.java:29)
	at org.gradle.profiler.ScenarioInvoker.runMeasured(ScenarioInvoker.java:[28](https://github.com/squareup/wallet/actions/runs/9328648814/job/25680061672#step:7:29))
	at org.gradle.profiler.gradle.GradleScenarioInvoker.run(GradleScenarioInvoker.java:121)
	at org.gradle.profiler.studio.invoker.StudioGradleScenarioInvoker.run(StudioGradleScenarioInvoker.java:63)
	at org.gradle.profiler.studio.invoker.StudioGradleScenarioInvoker.run(StudioGradleScenarioInvoker.java:19)
	at org.gradle.profiler.Main.invoke(Main.java:140)
	at org.gradle.profiler.Main.run(Main.java:98)
	at org.gradle.profiler.Main.main(Main.java:[37](https://github.com/squareup/wallet/actions/runs/9328648814/job/25680061672#step:7:38))

* Results written to /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out
  /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/benchmark.csv
  /Users/runner/work/wallet/wallet/app/gradle/benchmarks/_build/profile-out/benchmark.html
```

**Comment by ov7a** [comment]
Sorry for the late reply.

Judging by the log, it's a duplicate of
* https://github.com/gradle/gradle-profiler/issues/534

So, I'm closing this. I'm having issues reproducing this, though, will follow up in another issue.
