### ISSUE TITLE
Remove usage of org.gradle.util.GFileUtils

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle-profiler#568]
[PidCollector.java:16 calls org.gradle.util.GFileUtils](https://github.com/gradle/gradle-profiler/blob/1125b1ed8223d4f8f5ce57b4ac48232d6ce65b53/subprojects/build-operations/src/main/java/org/gradle/trace/pid/PidCollector.java#L12) and that method has been deprecated and will be removed in Gradle 9.0

https://ge.androidx.dev/s/nzodz7gwiblhy/deprecations?expanded=WyIyNCIsIjQiXQ&expanded-stacktrace=WyIyNiJd

**Comment by adecker89** [comment]
I'm not sure how, but I'm still getting an error that looks related to this when using 0.22.0 on gradle 9.0 (at least for the prebuilt version https://repo1.maven.org/maven2/org/gradle/profiler/gradle-profiler/0.22.0/gradle-profiler-0.22.0.zip, I haven't tried compiling yet) 

```
> ./gradle-profiler --benchmark --project-dir {} :help
Caused by: java.lang.NoClassDefFoundError: org/gradle/util/GFileUtils
	at org.gradle.trace.pid.PidCollector.collect(PidCollector.java:16)
	at gradleProfiler1843102736759570_bg9xw3yuxnkboxfcnencs3916.run(/private/var/folders/n_/xw5m1pcd1m3dj_6lybpfhsn80000gn/T/gradleProfiler18431027367595702146.gradle:7)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 143 more
Caused by: java.lang.ClassNotFoundException: org.gradle.util.GFileUtils
	at org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader.findClass(VisitableURLClassLoader.java:189)
```

```
> ./gradle-profiler --version
Gradle Profiler version 0.22.0
```

**Comment by adecker89** [comment]
Confirmed that things seem fine when built from source, so I'm not sure what's up with the built artifact.

**Comment by kimjinyam** [comment]
I also encountered the same issue at using gradle-profiler 0.19.0 on gradle 9.0

However, using `0.23.0-alpha-1` fixed the issue.

**Comment by emartynov** [comment]
So 0.22.0 is not a version for the fix yet?

**Comment by emartynov** [comment]
> So 0.22.0 is not a version for the fix yet?

No and I should wait for 0.23.0.

When is 0.23.0 planned to be released?

@liutikas do you use alpha version of profiler now?

**Comment by asodja** [comment]
Gradle-profiler 0.23.0 was just released.
https://github.com/gradle/gradle-profiler/releases/tag/v0.23.0
