### ISSUE TITLE
Keep getting an failure with latest master of profiler and Gradle

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-profiler#88]
I keep having this failure and I don't know what is causing it. I tried various mix JDK without success. I'm not sure if this is an issue or a miss configuration.
```
java.lang.RuntimeException: Could not run command /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/jcmd 43326 JFR.start name=profile settings=/var/folders/rg/y7myh0qj1sd58f02v_tgypvh0000gn/T/gradle1191992045150061660.jfc. Exited with result 1
	at org.gradle.profiler.CommandExec$RunHandle.waitForSuccess(CommandExec.java:182)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:81)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:35)
	at org.gradle.profiler.jfr.JFRControl.run(JFRControl.java:56)
	at org.gradle.profiler.jfr.JFRControl.doStartRecording(JFRControl.java:39)
	at org.gradle.profiler.SingleIterationProfilerController.startRecording(SingleIterationProfilerController.java:20)
	at org.gradle.profiler.Main.lambda$runGradleScenario$1(Main.java:221)
	at org.gradle.profiler.Main.tryRun(Main.java:422)
	at org.gradle.profiler.Main.runGradleScenario(Main.java:218)
	at org.gradle.profiler.Main.run(Main.java:80)
	at org.gradle.profiler.Main.main(Main.java:27)
```

**Comment by oehme** [comment]
Can you look at the output of jcmd to see what's wrong?

**Comment by oehme** [comment]
Closing for inactivity
